// <auto-generated />
using System;
using Clean4ork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clean4ork.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926210625_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clean4ork.Core.Domain.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("BusinessEntityName")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacilityType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SnapshotInspectionDate")
                        .HasColumnType("date");

                    b.Property<string>("SnapshotInspectionReason")
                        .HasColumnType("text");

                    b.Property<bool?>("SnapshotPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceFacilityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataTier");

                    b.HasIndex("PostalCode");

                    b.HasIndex("Jurisdiction", "Slug")
                        .IsUnique();

                    b.HasIndex("Jurisdiction", "SourceFacilityId")
                        .IsUnique();

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<string>("InspectorName")
                        .HasColumnType("text");

                    b.Property<string>("SourceInspectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryNotes")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InspectionDate");

                    b.HasIndex("EstablishmentId", "SourceInspectionId")
                        .IsUnique();

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.InspectionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<char?>("NewGrade")
                        .HasColumnType("character(1)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char?>("PreviousGrade")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("AlertedAt");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("InspectionEvents");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.Violation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<string>("OrdinanceCitation")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("InspectionId");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.Inspection", b =>
                {
                    b.HasOne("Clean4ork.Core.Domain.Establishment", "Establishment")
                        .WithMany("Inspections")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.InspectionEvent", b =>
                {
                    b.HasOne("Clean4ork.Core.Domain.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.Violation", b =>
                {
                    b.HasOne("Clean4ork.Core.Domain.Inspection", "Inspection")
                        .WithMany("Violations")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.Establishment", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("Clean4ork.Core.Domain.Inspection", b =>
                {
                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
